version: "3.8"
services:
  website:
    build: ./website
    command: gunicorn -b 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
  nginx:
    build: ./ngnix
    ports:
      - "80:80"
    depends_on:
      - website