name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          APP_NAME: ${{ secrets.APP_NAME }}

        run: |
          echo "$SSH_KEY" > super_dooper_secret_key && sudo chmod 600 super_dooper_secret_key
          ssh -o StrictHostKeyChecking=no -i super_dooper_secret_key ${USERNAME}@${HOST} << 'ENDSSH'
            cd project/Home 
            sudo systemctl stop ${APP_NAME}
            sudo git pull
            sudo systemctl start ${APP_NAME}
            sudo systemctl restart nginx
          ENDSSH